server:
  port: 10000
  servlet:
    context-path: /empthymeleaf
    
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false    
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/manageemp?characterEncoding=UTF-8
    username: root
    password: 123456
  web:
    resources:
      static-locations: classpath:/static/,file:${file.upload.dir}
    
mybatis:
  mapper-locations:  classpath:com/eden/mapper/*.xml
  type-aliases-package:  com.eden.entity
  
file: 
 upload: 
  dir: C:\\Java2023\\workspace\\0620\\manageemp\\upload
  
logging:
  level:
   root: info
   '[com.eden]': debug
    